[package]
name = "dlna-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core types and SSDP for DLNA library"

[dependencies]
tokio.workspace = true
futures.workspace = true
rupnp.workspace = true
serde.workspace = true
uuid.workspace = true
url.workspace = true
local-ip-address.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
socket2.workspace = true
mime_guess.workspace = true
quick-xml.workspace = true
toml.workspace = true
dirs.workspace = true
libc.workspace = true
hostname.workspace = true
